### PR TITLE
Throw a different error when baseline is missing and acceptFirstBaseline is false

### LINKED ISSUE #49: Throw a different error when baseline is missing and acceptFirstBaseline is false
## Need

```gherkin
As a user
I want clear error messages
So that I can quickly identify what the problem is.
```

## Deliverables

```gherkin
Given that there is no baseline
And `acceptFirstBaseline` is set to `false`
When I run mugshot
Then it will throw with an error telling me that the baseline is missing.
```

## Solution

Don't [call](https://github.com/uberVU/mugshot/blob/fc8953ee445c829ee4df31d8575dfa4c91bcb82d/lib/mugshot.js#L279-L282) the `done` callback with no error when `acceptFirstBaseline` is `false`.

```js
if (acceptFirstBaseline) {
  done(null, {isEqual: true, baseline: baselinePath});
} else {
  done(new Error('Baseline missing'));
}
```

#### TODO

- [x] write failing test
- [x] make it pass

### PR DESCRIPTION
**Pull request by adela-istrate-hs**
Closes #49

### CODE REVIEW

File: lib/mugshot.js [hunk 1]
```diff
@@ -276,10 +276,11 @@ function _test(baseName, options, screenshot, done) {
...
         }
 
-        done(null, {
-          isEqual: options.acceptFirstBaseline,
-          baseline: baselinePath
-        });
+        if (options.acceptFirstBaseline) {
+          done(null, {isEqual: true, baseline: baselinePath});
+        } else {
+          done(new Error('Baseline missing'));
```
Comment (adela-istrate-hs) [inline lib/mugshot.js]: @andrei-picus-hs Should I leave it like this or should I return the result object too?

Comment (andrei-picus-hs) [inline lib/mugshot.js]: The convention is that when an error occurs you can't expect any useful/relevant information in the result object so it's ok to just not return it.

**Comment by adela-istrate-hs** [comment]
@andrei-picus-hs  @valentin-radulescu-hs Is it ok? Can I merge?

File: tests/unit/no-baseline.js [hunk 2]
```diff
@@ -93,12 +93,9 @@ describe('No baseline', function() {
...
     var mugshot = new Mugshot(browser, options);
-    var result = {
-      isEqual: false,
-      baseline: baselinePath
-    };
 
     mugshot.test(noSelector, callback);
-    expect(callback).to.have.been.calledWithExactly(null, result);
+    expect(callback)
+        .to.have.been.calledWithExactly(new Error('Baseline missing'));
```
Comment (andrei-picus-hs) [inline tests/unit/no-baseline.js]: I would use `calledWith` instead because we don't really care about the results object.

File: tests/integration/test.js [hunk 3]
```diff
@@ -176,24 +172,16 @@ describe('Mugshot integration with disabled acceptFirstBaseline', function() {
...
-     'baseline', function(done) {
+  it('should throw an error and results to be undefined if there is no' +
+  ' baseline', function(done) {
     cleanUp();
 
     mugshot.test(noDifferencesSelector, function(error, result) {
-      expect(error).to.be.null;
-      expect(result).to.be.deep.equal(noBaselineResult);
+      expect(error).to.be.an.instanceof(Error);
+      expect(result).to.be.undefined;
```
Comment (andrei-picus-hs) [inline tests/integration/test.js]: We don't care about this so just remove the assertion and update the test name.

**Comment by andrei-picus-hs** [comment]
Finished review.

**Comment by valentin-radulescu-hs** [comment]
LGTM

**Comment by adela-istrate-hs** [comment]
@andrei-picus-hs Can I merge?

**Comment by andrei-picus-hs** [comment]
LGTM
